javax.persistence.jdbc.url=jdbc:mysql://localhost:3306/ch_labs_hibernate_01
javax.persistence.jdbc.user=root
javax.persistence.jdbc.password=manish
javax.persistence.jdbc.driver=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update
